### ISSUE TITLE
Toggle positional box in does not properly update layout

### ISSUE THREAD

**Issue by flekschas** [hms-dbmi/higlass#11]
_Commit_: fb2d74a16847e116c25b9608f0d6964f72223254

#### Steps to reproduce
1. Click on the heatmnap's cog wheel and then on _settings_

#### Observed behavior

```
hglib.js:9 Uncaught TypeError: e.props.onClick is not a function
    at onClick (http://localhost:3000/assets/scripts-third-party/hglib.js:9:6802)
    at Object.o.invokeGuardedCallback (http://localhost:3000/assets/scripts-third-party/hglib.js:33:3294)
    at a (http://localhost:3000/assets/scripts-third-party/hglib.js:32:27815)
    at Object.s [as executeDispatchesInOrder] (http://localhost:3000/assets/scripts-third-party/hglib.js:32:28066)
    at h (http://localhost:3000/assets/scripts-third-party/hglib.js:10:16691)
    at d (http://localhost:3000/assets/scripts-third-party/hglib.js:10:16817)
    at Array.forEach (native)
    at n (http://localhost:3000/assets/scripts-third-party/hglib.js:60:14217)
    at Object.processEventQueue (http://localhost:3000/assets/scripts-third-party/hglib.js:10:17932)
    at r (http://localhost:3000/assets/scripts-third-party/hglib.js:91:31862)
    at Object.handleTopLevel [as _handleTopLevel] (http://localhost:3000/assets/scripts-third-party/hglib.js:91:31964)
```

#### Expected behavior
- No error

**Comment by pkerpedjiev** [comment]
There's no `settings` entry under the heatmap's cog wheel.
