### ISSUE TITLE
Custom color maps broken on HiGlass.io

### ISSUE THREAD

**Issue by flekschas** [hms-dbmi/higlass#116]
_Commit_: http://higlass.io/ or v0.8.2

#### Steps to reproduce
1. Try to open the custom color map editor

#### Observed behavior
- Nothing happens

The console says:
```
HiGlassComponent.jsx:1741 Uncaught TypeError: Cannot read property 'h' of undefined
    at HiGlassComponent.adjustLayoutToTrackSizes (http://localhost:8080/hglib.js:15408:43)
    at http://localhost:8080/hglib.js:13812:26
    at Array.map (native)
    at new HiGlassComponent (http://localhost:8080/hglib.js:13811:107)
    at p._constructComponentWithoutOwner (https://cdnjs.cloudflare.com/ajax/libs/react/15.5.4/react-dom.min.js:13:6309)
    at p._constructComponent (https://cdnjs.cloudflare.com/ajax/libs/react/15.5.4/react-dom.min.js:13:6176)
    at p.mountComponent (https://cdnjs.cloudflare.com/ajax/libs/react/15.5.4/react-dom.min.js:13:5358)
    at Object.mountComponent (https://cdnjs.cloudflare.com/ajax/libs/react/15.5.4/react-dom.min.js:14:18841)
    at h.mountChildren (https://cdnjs.cloudflare.com/ajax/libs/react/15.5.4/react-dom.min.js:14:15474)
    at h._createInitialChildren (https://cdnjs.cloudflare.com/ajax/libs/react/15.5.4/react-dom.min.js:13:19534)
    at h.mountComponent (https://cdnjs.cloudflare.com/ajax/libs/react/15.5.4/react-dom.min.js:13:17748)
```

#### Expected behavior
- The colormap editor should open

**Comment by pkerpedjiev** [comment]
Verified fixed in v0.8.23.

**Comment by flekschas** [comment]
Works for the center track but not the horizontal heatmap:

SERVER_VERSION: 1.2.1
WEBSITE_VERSION: 0.6.9
LIBRARY_VERSION: 0.8.34

Also, on the center custom colormap popup the `X` button on the top right is broken

**Comment by pkerpedjiev** [comment]
No longer an issue.
