### ISSUE TITLE
cooler ingestion

### ISSUE THREAD

**Issue by Phlya** [hms-dbmi/higlass#177]
Hi, I guess this is more of a question than an issue, please let me know if there is a more appropriate place to ask them.

What happens when a cooler file is ingested? For example, I put the file into /tmp volume of the docker container, then ingest it. What I observe is it gets copied into the /data folder, and potentially renamed if there is a cooler with the same name there already. So, does anything else happen to it, except, I guess, it's added to the database? Why does it have to be copied? Can I ingest directly from the /data folder? (All examples show only the use of /tmp for this - I guess it's easy to try myself though).

Also, when I remove the dataset using the admin interface the file stays in the folder and I have to manually remove it with sudo - is this intended behaviour?

Sorry if it's all not very coherent, I am just trying to get a hang of what's going on, and whether I can do things more efficiently.

**Comment by pkerpedjiev** [comment]
These are great questions!

When a cooler gets ingested it gets copied into the /data/hg-data/media/uploads directory. We did this for security, ease and deployment purposes. We figured that if we could let people upload from any location, they need not worry what the server did with the files and where it put them. When removing files from the admin interface, we don't remove them from the data directory. This was meant to prevent wrongful deletions. So that if you accidentally deleted something from the admin interface your file didn't accidentally go with it too. In retrospect, I think these design decisions may have been a little too cautious and we'll likely change them in the future (while remaining backwards compatible). We were also planning on releasing a script that would clean up the data directory by seeing which data files were absent from the database.

To answer your question about ingesting without copying, it is indeed possible. Just place your data file within the media directory and ingest with a path relative to that and the `--no-upload` option.

```
cp file.cool /data/hg-data/media/my_cools/
sudo docker exec higlass-container python higlass-server/manage.py \
  ingest_tileset \
  --filename my_cools/file.cool \
  --datatype matrix \
  --filetype cooler \
  --no-upload
```

Hope that helps! If anything else is unclear, please don't hesitate to ask.

**Comment by Phlya** [comment]
Thanks a lot! This clears things up, I might change some locations in my setup then to make everything a bit easier.

**Comment by Phlya** [comment]
OK, I tried this, and I get an error:
```
s1529682:~$ docker run --detach --publish 8989:80 --volume ~/Datastore/wendy-lab/ilia/data/Hi-C/hg-data:/data --name higlass-container gehlenborglab/higlass
6b1bad6a894b817891906e72b1c16332b3973073774cff030e1a2ef5e6142272
s1529682:~$ docker exec higlass-container python higlass-server/manage.py ingest_tileset --filename multicools/npc_1Kb.multi.cool --datatype matrix --filetype cooler --no-upload
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/opt/conda/lib/python3.6/site-packages/django/db/backends/sqlite3/base.py", line 328, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: no such table: tilesets_tileset

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "higlass-server/manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/conda/lib/python3.6/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/opt/conda/lib/python3.6/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/conda/lib/python3.6/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/conda/lib/python3.6/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/home/higlass/projects/higlass-server/tilesets/management/commands/ingest_tileset.py", line 63, in handle
    name=name)
  File "/opt/conda/lib/python3.6/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/django/db/models/query.py", line 394, in create
    obj.save(force_insert=True, using=self.db)
  File "/opt/conda/lib/python3.6/site-packages/django/db/models/base.py", line 808, in save
    force_update=force_update, update_fields=update_fields)
  File "/opt/conda/lib/python3.6/site-packages/django/db/models/base.py", line 838, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/opt/conda/lib/python3.6/site-packages/django/db/models/base.py", line 924, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/opt/conda/lib/python3.6/site-packages/django/db/models/base.py", line 963, in _do_insert
    using=using, raw=raw)
  File "/opt/conda/lib/python3.6/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/django/db/models/query.py", line 1076, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/opt/conda/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1107, in execute_sql
    cursor.execute(sql, params)
  File "/opt/conda/lib/python3.6/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/opt/conda/lib/python3.6/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/opt/conda/lib/python3.6/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/opt/conda/lib/python3.6/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/opt/conda/lib/python3.6/site-packages/django/db/backends/sqlite3/base.py", line 328, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such table: tilesets_tileset
```

**Comment by pkerpedjiev** [comment]
That's strange! Perhaps you could run `curl localhost:8989/api/v1/tilesets/` before running the ingest command?

I'm thinking that if you started the docker container pointing to a database directory that didn't already have a database, it would lead to this error. The curl command tries to retrieve something from the database causing it to be created.

Also, could you check which version of the Docker container you're running? The latest is `v0.2.41`.

**Comment by Phlya** [comment]
What do you mean, "started the docker container pointing to a database directory that didn't already have a database"? How do I create a database then?

I pulled the latest version, started higlass and tried the curl command, and don't think it helped...
```
s1529682:~$ docker run --detach --publish 8989:80 --volume ~/Datastore/wendy-lab/ilia/data/Hi-C/hg-data:/data --name higlass-container gehlenborglab/higlass
26c34dd00d63fe0718f349e46e90dc4db05c15bd0a4d75540a59fe2fb8d0db07
s1529682:~$ curl localhost:8989/api/v1/tilesets/
<html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.6.2</center>
</body>
</html>
s1529682:~$ docker exec higlass-container python higlass-server/manage.py ingest_tileset --filename multicools/npc_1Kb.multi.cool --datatype matrix --filetype cooler --no-upload
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/opt/conda/lib/python3.6/site-packages/django/db/backends/sqlite3/base.py", line 328, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: no such table: tilesets_tileset

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "higlass-server/manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/conda/lib/python3.6/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/opt/conda/lib/python3.6/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/conda/lib/python3.6/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/conda/lib/python3.6/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/home/higlass/projects/higlass-server/tilesets/management/commands/ingest_tileset.py", line 63, in handle
    name=name)
  File "/opt/conda/lib/python3.6/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/django/db/models/query.py", line 394, in create
    obj.save(force_insert=True, using=self.db)
  File "/opt/conda/lib/python3.6/site-packages/django/db/models/base.py", line 808, in save
    force_update=force_update, update_fields=update_fields)
  File "/opt/conda/lib/python3.6/site-packages/django/db/models/base.py", line 838, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/opt/conda/lib/python3.6/site-packages/django/db/models/base.py", line 924, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/opt/conda/lib/python3.6/site-packages/django/db/models/base.py", line 963, in _do_insert
    using=using, raw=raw)
  File "/opt/conda/lib/python3.6/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/django/db/models/query.py", line 1076, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/opt/conda/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1107, in execute_sql
    cursor.execute(sql, params)
  File "/opt/conda/lib/python3.6/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/opt/conda/lib/python3.6/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/opt/conda/lib/python3.6/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/opt/conda/lib/python3.6/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/opt/conda/lib/python3.6/site-packages/django/db/backends/sqlite3/base.py", line 328, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such table: tilesets_tileset
```

**Comment by pkerpedjiev** [comment]
Ah, sorry. So when you start the Docker container with "--volume 
~/Foo:/data" it usually creates a database in that directory. That's why 
when you restart it, all your data will still be there. I just wasn't sure 
exactly when that database was created: when the docker container was 
started or when the first API call was issued. I'm actually still not sure.

Unfortunately, I'm going to be AFK for most of the weekend but I can take a 
closer look Sunday evening.

**Comment by Phlya** [comment]
OK, is there a way to create this database? I remember I have seen this error before, actually, but it somehow solved itself...

**Comment by pkerpedjiev** [comment]
There isn't a "sanctioned" way to do it manually. If you wanted to hack it, you could probably do something like:

`docker exec higlass-container higlass-server/manage.py migrate`

No guarantees on whether that will work. 

I've seen the "Bad Gateway" error sometimes after restarting the docker container. Usually hitting reload on the front page makes it go away. Perhaps try running `curl http://localhost:8989/api/v1/tilesets/`?

Maybe make sure that there's no other instances of the Docker container running at the same time?

**Comment by Phlya** [comment]
What I get sometimes is that the page loads, but there is no actual higlass instance there - like this
![screenshot from 2017-11-13 14-59-06](https://user-images.githubusercontent.com/2895034/32732002-3b1f6042-c883-11e7-823e-16c2ee22c67b.png)
Not sure how to fix this...

When I try the command you suggested I get this:
```
s1529682:~$ docker exec higlass-container higlass-server/manage.py migrate
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/django/db/backends/base/base.py", line 236, in _commit
    return self.connection.commit()
sqlite3.OperationalError: database is locked

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/django/db/migrations/recorder.py", line 57, in ensure_schema
    editor.create_model(self.Migration)
  File "/opt/conda/lib/python3.6/site-packages/django/db/backends/sqlite3/schema.py", line 30, in __exit__
    super(DatabaseSchemaEditor, self).__exit__(exc_type, exc_value, traceback)
  File "/opt/conda/lib/python3.6/site-packages/django/db/backends/base/schema.py", line 95, in __exit__
    self.atomic.__exit__(exc_type, exc_value, traceback)
  File "/opt/conda/lib/python3.6/site-packages/django/db/transaction.py", line 223, in __exit__
    connection.commit()
  File "/opt/conda/lib/python3.6/site-packages/django/db/backends/base/base.py", line 262, in commit
    self._commit()
  File "/opt/conda/lib/python3.6/site-packages/django/db/backends/base/base.py", line 236, in _commit
    return self.connection.commit()
  File "/opt/conda/lib/python3.6/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/opt/conda/lib/python3.6/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/opt/conda/lib/python3.6/site-packages/django/db/backends/base/base.py", line 236, in _commit
    return self.connection.commit()
django.db.utils.OperationalError: database is locked

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "higlass-server/manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/conda/lib/python3.6/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/opt/conda/lib/python3.6/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/conda/lib/python3.6/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/conda/lib/python3.6/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/opt/conda/lib/python3.6/site-packages/django/core/management/commands/migrate.py", line 83, in handle
    executor = MigrationExecutor(connection, self.migration_progress_callback)
  File "/opt/conda/lib/python3.6/site-packages/django/db/migrations/executor.py", line 20, in __init__
    self.loader = MigrationLoader(self.connection)
  File "/opt/conda/lib/python3.6/site-packages/django/db/migrations/loader.py", line 52, in __init__
    self.build_graph()
  File "/opt/conda/lib/python3.6/s1529682:~$ docker exec higlass-container higlass-server/manage.py migrate
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/django/db/backends/base/base.py", line 236, in _commit
    return self.connection.commit()
sqlite3.OperationalError: database is locked

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/django/db/migrations/recorder.py", line 57, in ensure_schema
    editor.create_model(self.Migration)
  File "/opt/conda/lib/python3.6/site-packages/django/db/backends/sqlite3/schema.py", line 30, in __exit__
    super(DatabaseSchemaEditor, self).__exit__(exc_type, exc_value, traceback)
  File "/opt/conda/lib/python3.6/site-packages/django/db/backends/base/schema.py", line 95, in __exit__
    self.atomic.__exit__(exc_type, exc_value, traceback)
  File "/opt/conda/lib/python3.6/site-packages/django/db/transaction.py", line 223, in __exit__
    connection.commit()
  File "/opt/conda/lib/python3.6/site-packages/django/db/backends/base/base.py", line 262, in commit
    self._commit()
  File "/opt/conda/lib/python3.6/site-packages/django/db/backends/base/base.py", line 236, in _commit
    return self.connection.commit()
  File "/opt/conda/lib/python3.6/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/opt/conda/lib/python3.6/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/opt/conda/lib/python3.6/site-packages/django/db/backends/base/base.py", line 236, in _commit
    return self.connection.commit()
django.db.utils.OperationalError: database is locked

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "higlass-server/manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/conda/lib/python3.6/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/opt/conda/lib/python3.6/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/conda/lib/python3.6/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/conda/lib/python3.6/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/opt/conda/lib/python3.6/site-packages/django/core/management/commands/migrate.py", line 83, in handle
    executor = MigrationExecutor(connection, self.migration_progress_callback)
  File "/opt/conda/lib/python3.6/site-packages/django/db/migrations/executor.py", line 20, in __init__
    self.loader = MigrationLoader(self.connection)
  File "/opt/conda/lib/python3.6/site-packages/django/db/migrations/loader.py", line 52, in __init__
    self.build_graph()
  File "/opt/conda/lib/python3.6/site-packages/django/db/migrations/loader.py", line 209, in build_graph
    self.applied_migrations = recorder.applied_migrations()
  File "/opt/conda/lib/python3.6/site-packages/django/db/migrations/recorder.py", line 65, in applied_migrations
    self.ensure_schema()
  File "/opt/conda/lib/python3.6/site-packages/django/db/migrations/recorder.py", line 59, in ensure_schema
    raise MigrationSchemaMissing("Unable to create the django_migrations table (%s)" % exc)
django.db.migrations.exceptions.MigrationSchemaMissing: Unable to create the django_migrations table (database is locked)

```site-packages/django/db/migrations/loader.py", line 209, in build_graph
    self.applied_migrations = recorder.applied_migrations()
  File "/opt/conda/lib/python3.6/site-packages/django/db/migrations/recorder.py", line 65, in applied_migrations
    self.ensure_schema()
  File "/opt/conda/lib/python3.6/site-packages/django/db/migrations/recorder.py", line 59, in ensure_schema
    raise MigrationSchemaMissing("Unable to create the django_migrations table (%s)" % exc)
django.db.migrations.exceptions.MigrationSchemaMissing: Unable to create the django_migrations table (database is locked)

**Comment by pkerpedjiev** [comment]
These are some next level errors you're getting. I'm really sorry that this is happening. Would it be possible for you to just try starting the docker container with a new, empty data directory and importing as usual?

So if you don't see the page loading, I would open the development console:

![image](https://user-images.githubusercontent.com/2143629/32738591-b05042ec-c85a-11e7-9562-10fd7f99799e.png)

And see which errors you get.

**Comment by Phlya** [comment]
Will try restarting everything.

What do I do in Firefox?..

**Comment by Phlya** [comment]
OK, if I do everything from scratch and use a /tmp folder ingestion works as expected.

**Comment by flekschas** [comment]
Closed as presumably resolved
